---
- name: Configure file - /etc/myhosts
  hosts: dev
  tasks:
    - name: Configure /etc/myhost
      template:
        src: templates/hosts.j2
        dest: /etc/myhosts
        owner: root
        group: root
        mode: '0644'